package com.foo.tourist.dao;

import com.gfyt.core.bean.entity.Test1;
import com.gfyt.core.storage.api.BaseDao;
import org.apache.ibatis.annotations.*;

public interface Test1Mapper extends BaseDao
{
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table test1
	 *
	 * @mbg.generated
	 */
	@Delete({ "delete from test1", "where tid = #{tid,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table test1
	 *
	 * @mbg.generated
	 */
	@Insert({ "insert into test1 (tid, tname)", "values (#{tid,jdbcType=INTEGER}, #{tname,jdbcType=VARCHAR})" })
	int insert(Test1 record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table test1
	 *
	 * @mbg.generated
	 */
	int insertSelective(Test1 record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table test1
	 *
	 * @mbg.generated
	 */
	@Select({ "select", "tid, tname", "from test1", "where tid = #{tid,jdbcType=INTEGER}" })
	@ResultMap("com.foo.tourist.dao.Test1Mapper.BaseResultMap")
	Test1 selectByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table test1
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Test1 record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table test1
	 *
	 * @mbg.generated
	 */
	@Update({ "update test1", "set tname = #{tname,jdbcType=VARCHAR}", "where tid = #{tid,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Test1 record);
}