package com.gfyt.core.storage.db.api;

import com.gfyt.core.bean.entity.Test1;
import com.gfyt.core.storage.api.BaseDao;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public interface Test1Mapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table framework..test1
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table framework..test1
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    int insert(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table framework..test1
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    int insertSelective(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table framework..test1
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    Test1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table framework..test1
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    int updateByPrimaryKeySelective(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table framework..test1
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    int updateByPrimaryKey(Test1 record);
}