spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    allowPublicKeyRetrieval:true
    url: jdbc:mysql://192.168.0.2:3306/framework?allowPublicKeyRetrieval=true
    username: framework_write
    password: framework_write