package com.gfyt.core.bean.entity;

import com.gfyt.core.bean.entity.core.BaseEntity;
import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Test extends BaseEntity {
    /**
     *   主键id
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @NotNull
    @Size(max = 10)
    private Integer id;

    /**
     *   test-name
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @NotNull
    @Size(max = 10)
    private String name;

    /**
     *   test age
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @NotNull
    @Size(max = 10)
    private Integer age;

    /**
     *   钱
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @Size(max = 10)
    private Integer money;

    /**
     *   虚拟动态生成列,钱*age
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @Size(max = 10)
    private Integer genmoney;

    /**
     *   虚拟动态生成持久列,钱*age*2
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @Size(max = 10)
    private Integer genmoney2;

    /**
     *   创建日期
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    @Size(max = 19)
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.NAME
     *
     * @return the value of test.NAME
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.NAME
     *
     * @param name the value for test.NAME
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.age
     *
     * @return the value of test.age
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.age
     *
     * @param age the value for test.age
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.money
     *
     * @return the value of test.money
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.money
     *
     * @param money the value for test.money
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.genMoney
     *
     * @return the value of test.genMoney
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public Integer getGenmoney() {
        return genmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.genMoney
     *
     * @param genmoney the value for test.genMoney
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setGenmoney(Integer genmoney) {
        this.genmoney = genmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.genMoney2
     *
     * @return the value of test.genMoney2
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public Integer getGenmoney2() {
        return genmoney2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.genMoney2
     *
     * @param genmoney2 the value for test.genMoney2
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setGenmoney2(Integer genmoney2) {
        this.genmoney2 = genmoney2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.createTime
     *
     * @return the value of test.createTime
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.createTime
     *
     * @param createtime the value for test.createTime
     *
    * @date  2018-09-29 17:04:44
    * @author
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}