package com.gfyt.core.bean.entity;

import com.gfyt.core.bean.entity.core.BaseEntity;
import java.util.Date;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Test1 extends BaseEntity {
    /**
     *   主键id
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @NotNull
    @Size(max = 10)
    private Integer id;

    /**
     *   test11-name 
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @NotNull
    @Size(max = 10)
    private String name;

    /**
     *   test11 age
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @NotNull
    @Size(max = 10)
    private Integer age;

    /**
     *   钱
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @Size(max = 10)
    private Integer money;

    /**
     *   虚拟动态生成列,钱*age 
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @Size(max = 10)
    private Integer genmoney;

    /**
     *   虚拟动态生成持久列,钱*age*2 
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @Size(max = 10)
    private Integer genmoney2;

    /**
     *   创建日期
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    @Size(max = 26)
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.id
     *
     * @return the value of framework..test1.id
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.id
     *
     * @param id the value for framework..test1.id
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.NAME
     *
     * @return the value of framework..test1.NAME
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.NAME
     *
     * @param name the value for framework..test1.NAME
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.age
     *
     * @return the value of framework..test1.age
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.age
     *
     * @param age the value for framework..test1.age
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.money
     *
     * @return the value of framework..test1.money
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.money
     *
     * @param money the value for framework..test1.money
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.genMoney
     *
     * @return the value of framework..test1.genMoney
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public Integer getGenmoney() {
        return genmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.genMoney
     *
     * @param genmoney the value for framework..test1.genMoney
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setGenmoney(Integer genmoney) {
        this.genmoney = genmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.genMoney2
     *
     * @return the value of framework..test1.genMoney2
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public Integer getGenmoney2() {
        return genmoney2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.genMoney2
     *
     * @param genmoney2 the value for framework..test1.genMoney2
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setGenmoney2(Integer genmoney2) {
        this.genmoney2 = genmoney2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column framework..test1.createTime
     *
     * @return the value of framework..test1.createTime
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column framework..test1.createTime
     *
     * @param createtime the value for framework..test1.createTime
     *
    * @date  2018-10-13 22:55:15
    * @author  hanxu
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}