SELECT
  *
FROM
  information_schema.COLUMNS
WHERE TABLE_NAME = 'jq22_user';


SELECT
  TABLE_SCHEMA                                   AS TABLE_CAT
  ,
  NULL                                           AS TABLE_SCHEM
  ,
  TABLE_NAME
  ,
  COLUMN_NAME
  ,
  CASE WHEN UPPER(DATA_TYPE) = 'FLOAT'
    THEN 7
  WHEN DATA_TYPE = 'FLOAT UNSIGNED'
    THEN 7
  WHEN UPPER(DATA_TYPE) = 'BLOB'
    THEN -4
  WHEN UPPER(DATA_TYPE) = 'SET'
    THEN 1
  WHEN UPPER(DATA_TYPE) = 'BINARY'
    THEN -2
  WHEN UPPER(DATA_TYPE) = 'DECIMAL'
    THEN 3
  WHEN DATA_TYPE = 'DECIMAL UNSIGNED'
    THEN 3
  WHEN UPPER(DATA_TYPE) = 'CHAR'
    THEN 1
  WHEN UPPER(DATA_TYPE) = 'TEXT'
    THEN -1
  WHEN UPPER(DATA_TYPE) = 'JSON'
    THEN 1
  WHEN UPPER(DATA_TYPE) = 'MEDIUMTEXT'
    THEN -1
  WHEN UPPER(DATA_TYPE) = 'INT'
    THEN 4
  WHEN UPPER(DATA_TYPE) = 'YEAR'
    THEN 91
  WHEN UPPER(DATA_TYPE) = 'TIMESTAMP'
    THEN 93
  WHEN UPPER(DATA_TYPE) = 'DOUBLE'
    THEN 8
  WHEN DATA_TYPE = 'DOUBLE UNSIGNED'
    THEN 8
  WHEN UPPER(DATA_TYPE) = 'TINYTEXT'
    THEN 12
  WHEN UPPER(DATA_TYPE) = 'TINYINT'
    THEN -6
  WHEN UPPER(DATA_TYPE) = 'LONGBLOB'
    THEN -4
  WHEN UPPER(DATA_TYPE) = 'INTEGER'
    THEN 4
  WHEN UPPER(DATA_TYPE) = 'GEOMETRY'
    THEN -2
  WHEN UPPER(DATA_TYPE) = 'ENUM'
    THEN 1
  WHEN UPPER(DATA_TYPE) = 'NUMERIC'
    THEN 3
  WHEN DATA_TYPE = 'NUMERIC UNSIGNED'
    THEN 3
  WHEN UPPER(DATA_TYPE) = 'LONGTEXT'
    THEN -1
  WHEN UPPER(DATA_TYPE) = 'BIGINT'
    THEN -5
  WHEN UPPER(DATA_TYPE) = 'TIME'
    THEN 92
  WHEN UPPER(DATA_TYPE) = 'MEDIUMINT'
    THEN 4
  WHEN UPPER(DATA_TYPE) = 'BIT'
    THEN -7
  WHEN UPPER(DATA_TYPE) = 'DATE'
    THEN 91
  WHEN UPPER(DATA_TYPE) = 'DATETIME'
    THEN 93
  WHEN UPPER(DATA_TYPE) = 'TINYBLOB'
    THEN -2
  WHEN UPPER(DATA_TYPE) = 'MEDIUMBLOB'
    THEN -4
  WHEN UPPER(DATA_TYPE) = 'SMALLINT'
    THEN 5
  WHEN UPPER(DATA_TYPE) = 'INT24'
    THEN 4
  WHEN UPPER(DATA_TYPE) = 'REAL'
    THEN 8
  WHEN UPPER(DATA_TYPE) = 'VARCHAR'
    THEN 12
  WHEN UPPER(DATA_TYPE) = 'VARBINARY'
    THEN -3
  ELSE 1111 END                                  AS DATA_TYPE
  ,
  UPPER(CASE WHEN LOCATE('unsigned', COLUMN_TYPE) != 0 AND LOCATE('unsigned', DATA_TYPE) = 0 AND LOCATE('set', DATA_TYPE) <> 1 AND LOCATE('enum', DATA_TYPE) <> 1
    THEN CONCAT(DATA_TYPE, ' unsigned')
        ELSE DATA_TYPE END)                      AS TYPE_NAME
  ,
  CASE WHEN LCASE(DATA_TYPE) = 'date'
    THEN 10
  WHEN LCASE(DATA_TYPE) = 'time'
    THEN 8
  WHEN LCASE(DATA_TYPE) = 'datetime'
    THEN 19
  WHEN LCASE(DATA_TYPE) = 'timestamp'
    THEN 19
  WHEN CHARACTER_MAXIMUM_LENGTH IS NULL
    THEN NUMERIC_PRECISION
  WHEN CHARACTER_MAXIMUM_LENGTH > 2147483647
    THEN 2147483647
  ELSE CHARACTER_MAXIMUM_LENGTH END              AS COLUMN_SIZE
  ,
  65535                                          AS BUFFER_LENGTH
  ,
  NUMERIC_SCALE                                  AS DECIMAL_DIGITS
  ,
  10                                             AS NUM_PREC_RADIX
  ,
  CASE WHEN IS_NULLABLE = 'NO'
    THEN 0
  ELSE CASE WHEN IS_NULLABLE = 'YES'
    THEN 1
       ELSE 2 END END                            AS NULLABLE
  ,
  COLUMN_COMMENT                                 AS REMARKS
  ,
  COLUMN_DEFAULT                                 AS COLUMN_DEF
  ,
  0                                              AS SQL_DATA_TYPE
  ,
  0                                              AS SQL_DATETIME_SUB
  ,
  CASE WHEN CHARACTER_OCTET_LENGTH > 2147483647
    THEN 2147483647
  ELSE CHARACTER_OCTET_LENGTH END                AS CHAR_OCTET_LENGTH
  ,
  ORDINAL_POSITION
  ,
  IS_NULLABLE
  ,
  NULL                                           AS SCOPE_CATALOG
  ,
  NULL                                           AS SCOPE_SCHEMA
  ,
  NULL                                           AS SCOPE_TABLE
  ,
  NULL                                           AS SOURCE_DATA_TYPE
  ,
  IF(EXTRA LIKE '%auto_increment%', 'YES', 'NO') AS IS_AUTOINCREMENT
  ,
  IF(EXTRA LIKE '%GENERATED%', 'YES', 'NO')      AS IS_GENERATEDCOLUMN
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = ? AND TABLE_NAME LIKE '%' AND COLUMN_NAME LIKE '%'
ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;