mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    hikari:
      data-source-properties:
        useSSL: false
        useUnicode: true
        characterEncoding: utf-8