package com.gfyt.core.bean.entity;

public class Test1 extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.tid
     *
     * @mbg.generated
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.tname
     *
     * @mbg.generated
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    public Test1(Integer tid, String tname) {
        this.tid = tid;
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.tid
     *
     * @return the value of test1.tid
     *
     * @mbg.generated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.tname
     *
     * @return the value of test1.tname
     *
     * @mbg.generated
     */
    public String getTname() {
        return tname;
    }
}